### ISSUE TITLE
Some ideas for improving the addon

### ISSUE THREAD

**Issue by gegelson** [Jaliborc/Combuctor#84]
These ideas I had already sent by the wow interface more like you envisioned will return here.
- Customizable Tabs: specific types for example relics of artifact or pets;
- A new items tab or some sort of twinkle in recent item;
- The new items tab or some sort of twinkle in recent item;
- Show coins at the bottom of the addon;
- Join all items the same in a single stack to reduce spaces;
- A system of profile to configure on each character the addon.

**Comment by ggiovannelli** [comment]
* possibility to save and reuse (dropdown menu) the searches or make them into a tab, like: 
tt:Artifact Power 

:)
